# Generated by Django 2.2.4 on 2019-08-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190804_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='super_deals',
            field=models.BooleanField(default=False, verbose_name='Do you want this item to display in super deals section?'),
        ),
    ]
