# Generated by Django 2.2.4 on 2019-08-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_super_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='Does this item have an offer?'),
        ),
    ]
