# Generated by Django 2.2.4 on 2019-08-10 16:44

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productimage_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='detail',
            field=image_cropping.fields.ImageRatioField('image', '351x371', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='icon',
            field=image_cropping.fields.ImageRatioField('image', '48x48', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='icon'),
        ),
    ]
